package com.crionics.blowfish;


/**
 * @todo: describe the class
 */
public class BlowfishException extends Exception
{

  /**
   * @todo: describe constructor
   * @param p0 todo: describe parameter
   */
  public BlowfishException(String p0)
  {
    super( p0);
  }

  /**
   * @todo: describe constructor
   */
  public BlowfishException()
  {
    super();
  }

}

/*
 * This class is autogenerated by ClassWizard, written by Joachim Nilsson in April/May 2001.
 * This software is provided "as is" with no warranty of any kind.
 */

