/*
 * WelcomeScreen.java
 *
 * 
 */


import java.io.*;
import java.security.*;
import javax.swing.JOptionPane;

/**
 *
 * @author  Xiang Dai (1108866)
 */
public class WelcomeScreen extends javax.swing.JFrame {
    
    /** Creates new form WelcomeScreen */
    public WelcomeScreen() {
        initComponents();
        setSize(450,300);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLblPassword = new javax.swing.JLabel();
        jBtnOpen = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();
        jProgramPassword = new javax.swing.JPasswordField();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setText("Password Manager");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 40, 270, 80);

        jLblPassword.setText("Password");
        getContentPane().add(jLblPassword);
        jLblPassword.setBounds(70, 130, 110, 20);

        jBtnOpen.setText("Login");
        jBtnOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnOpenMouseClicked(evt);
            }
        });

        getContentPane().add(jBtnOpen);
        jBtnOpen.setBounds(70, 190, 120, 25);

        jBtnClose.setText("Close");
        jBtnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCloseMouseClicked(evt);
            }
        });

        getContentPane().add(jBtnClose);
        jBtnClose.setBounds(210, 190, 120, 25);

        getContentPane().add(jProgramPassword);
        jProgramPassword.setBounds(190, 130, 150, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCloseMouseClicked
        System.exit(1);
    }//GEN-LAST:event_jBtnCloseMouseClicked

    private void jBtnOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnOpenMouseClicked
        try {
            File passFile = new File("loginpass.pm");
            MessageDigest md = MessageDigest.getInstance("SHA");
            if (!passFile.exists())
            {

                    passFile.createNewFile();
                    FileOutputStream fos = new FileOutputStream(passFile);
                    fos.write(md.digest(jProgramPassword.getText().getBytes()));
                    fos.close();
                    (new PasswordManagerGUI(jProgramPassword.getText())).setVisible(true);
                    setVisible(false);
            }
            else
            {
                FileInputStream xfis = new FileInputStream(passFile);
                
                File t = new File("temp.pm");
                t.createNewFile();
                FileOutputStream xfos = new FileOutputStream(t);
                xfos.write(md.digest(jProgramPassword.getText().getBytes()));
                xfos.close();
                FileInputStream f = new FileInputStream(t);
                for (int i=0; i < md.digest(jProgramPassword.getText().getBytes()).length; i++)
                {
                    if (f.read() != xfis.read())
                    {
                        JOptionPane.showMessageDialog(null,"Incorrect Password!");
                        break;
                    }
                    else if (i == md.digest(jProgramPassword.getText().getBytes()).length - 1)
                    {
                        (new PasswordManagerGUI(jProgramPassword.getText())).setVisible(true);
                        setVisible(false);
                    }
                }
                
                
            }
        } catch (Exception ex) {
                ex.printStackTrace();
        }
    }//GEN-LAST:event_jBtnOpenMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        File passFile = new File("loginpass.pm");
        if (!passFile.exists())
        {
            jLblPassword.setText("Create Password");
        }
    }//GEN-LAST:event_formWindowOpened
    
    private byte[] intToByteArray (final int integer) throws IOException {	
      ByteArrayOutputStream bos = new ByteArrayOutputStream();
      DataOutputStream dos = new DataOutputStream(bos);
      dos.writeInt(integer);
      dos.flush();
      return bos.toByteArray();
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnOpen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblPassword;
    private javax.swing.JPasswordField jProgramPassword;
    // End of variables declaration//GEN-END:variables
    
}
